---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:15.1  # Adjust the version as needed
        name: postgres
        env:
        - name: POSTGRES_DB
          value: "ecomappdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin123"  # Consider using Secrets for better security
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomapp
  template:
    metadata:
      labels:
        app: ecomapp
    spec:
      containers:
      - name: ecomapp
        image: iscanprint/ecomapp:3.2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/ecomappdb  # Updated URL for PostgreSQL
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin123  # Consider using Secrets for better security
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: ecomapp-service
spec:
  type: NodePort   # LoadBalancer if needed
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ecomapp
